function pcap2matlab_example()
%% Set up the capturing/reading parameters:
read_what = {'gvsp.status',...
             'gvsp.blockid16',...
             'gvsp.format',...
             'gvsp.packetid24',...
             'gvsp.fieldid',...
             'gvsp.fieldcount',...
             'gvsp.timestamp',...
             'gvsp.pixel.color','gvsp.pixel.occupy','gvsp.pixel.id',...
             'gvsp.sizex','gvsp.sizey',...
             'gvsp.offsetx','gvsp.offsety',...
             'gvsp.paddingx','gvsp.paddingy',...
             'gvsp.payloaddata','gvsp.payloadtype'};
%% Capture/read:         
pcap_result = pcap2matlab('gvsp',read_what,'gigE_image.pcapng');
keyboard;
%% Verify payload:
% Check that all data is present:
  % TODO
%% Analyze result:  
% Rebuild image data:
img_bin = hexToBinaryVector([pcap_result([pcap_result.gvsp_format] == 3).gvsp_payloaddata]);
im_bi_v = reshape(img_bin,pcap_result(1).gvsp_pixel_occupy,[]).';
img = uint16(bi2de(im_bi_v,'left-msb'));
% Plot:
IM16 = reshape(img,640,[]).';
IM14 = reshape(bitshift(img,-2),640,[]).';
figure();
subplot(2,2,1); imagesc(IM16); axis image; colorbar
subplot(2,2,2); imagesc(IM14); axis image; colorbar
subplot(2,2,3); histogram(IM16(:),intmax('uint16')); %alt: numel(unique(img));
subplot(2,2,4); histogram(IM14(:),intmax('uint16')/4);